version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: favorites
    ports:
      - '3003:3000'
      - '5533:5555'
    volumes:
      - .:/home/node/app
